swagger: '2.0'
tags:
  - name: Text Processing
get:
  description: Teks yang sudah dicleansing
responses:
    '200':
      description: Successful response
    '400':
      description: Bad Request
    '500':
      description: Internal Server Error
parameters:
  - name: body
    in: body
    schema:
      required:
        - text
      properties:
        text:
          type: string
          description: input your text
    
